name       : guake
version    : 3.9.0
release    : 20
source     :
    - git|https://github.com/Guake/guake.git : 3.9.0
license    : GPL-2.0-or-later
component  : programming.tools
summary    : Dropdown terminal utilizing Gnome-terminal
description: |
    Guake is a top-down terminal for Gnome, and is highly inspirated by the famous terminal used in quake
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(keybinder-3.0)
    - pkgconfig(py3cairo)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - pkgconfig(vte-2.91)
    - pbr
    - pyxdg
    - python3-dbus
    - python-setuptools-scm
rundeps    :
    - keybinder
    - libnotify
    - libutempter
    - libvte
    - libwnck
    - pbr
    - python3-dbus
    - python-gobject
    - pyxdg
    - pyyaml
build      : |
    %make
install    : |
    %make_install PREFIX=/usr COMPILE_SCHEMA=0
    install -Dm00644 -t $installdir/usr/share/pixmaps/guake/ guake/data/pixmaps/*.png
