name       : guake
version    : 0.8.8
release    : 4
source     :
    - https://github.com/Guake/guake/archive/0.8.8.tar.gz : 7f46422dcf1ca6a9bf712d9a02f0d9efb44902a25fa42bbf9ead3986419f1a28
license    : GPL-2.0
component  : programming.tools
summary    : Dropdown terminal utilizing Gnome-terminal
description: |
    Guake is a top-down terminal for Gnome, and is highly inspirated by the famous terminal used in quake
builddeps  :
    - pkgconfig(dbus-python)
    - pkgconfig(gconf-2.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(keybinder-3.0)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - pkgconfig(pyvte)
    - gnome-common
    - python-notifier
    - pyxdg
rundeps    :
    - gnome-python
    - keybinder
    - libutempter
    - notify-python
    - pyxdg
    - vte2
setup      : |
    %patch -p1 < $pkgfiles/0001-remove-vte-check.patch
    %autogen
build      : |
    %make
install    : |
    %make_install
