name       : guake
version    : 3.4.0
release    : 8
source     :
    - git|https://github.com/Guake/guake.git : 3.4.0
license    : GPL-2.0-or-later
component  : programming.tools
summary    : Dropdown terminal utilizing Gnome-terminal
description: |
    Guake is a top-down terminal for Gnome, and is highly inspirated by the famous terminal used in quake
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(keybinder-3.0)
    - pkgconfig(py3cairo)
    - pkgconfig(python3)
    - pkgconfig(vte-2.91)
    - pbr
    - python-notifier
    - pyxdg
    - python3-dbus
    - python3-gobject-devel
rundeps    :
    - keybinder
    - libutempter
    - libvte
    - notify-python
    - pbr
    - python3-cairo
    - python3-dbus
    - python3-gobject
    - pyxdg
build      : |
    %make
install    : |
    %make_install prefix=/usr COMPILE_SCHEMA=0
    install -Dm00644 -t $installdir/usr/share/pixmaps/guake/ data/pixmaps/*.png
