name       : guake
version    : 3.0.4
release    : 6
source     :
    - git|https://github.com/Guake/guake.git : 3.0.4
license    : GPL-2.0
component  : programming.tools
summary    : Dropdown terminal utilizing Gnome-terminal
description: |
    Guake is a top-down terminal for Gnome, and is highly inspirated by the famous terminal used in quake
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(keybinder-3.0)
    - pkgconfig(py3cairo)
    - pkgconfig(python3)
    - pkgconfig(vte-2.91)
    - pbr
    - python-notifier
    - pyxdg
    - python3-dbus
    - python3-gobject-devel
rundeps    :
    - keybinder
    - libutempter
    - libvte
    - notify-python
    - python3-cairo
    - python3-dbus
    - python3-gobject
    - pyxdg
setup      : |
    %patch -p1 < $pkgfiles/0001-Enforce-system-paths.patch
    sed -i "s:PACKAGE_VERSION:$version:g" guake/__init__.py
build      : |
    %python3_setup
    %make generate-desktop generate-mo
install    : |
    %python3_install
    %make install-schemas install-locale INSTALL_ROOT=$installdir/
    install -Dm00644 -t $installdir/usr/share/pixmaps/guake/ guake/data/pixmaps/*.png 
    install -Dm00644 -t $installdir/usr/share/guake/ guake/data/*.glade
