name       : guake
version    : 0.8.7
release    : 2
source     :
    - https://github.com/Guake/guake/archive/0.8.7.tar.gz : ea8df0091ff95ac337f3cd6ce144b56828a40c377416ede21a70985be784f5b0
license    : GPL-2.0
component  : programming.tools
summary    : Dropdown terminal utilizing Gnome-terminal
description: |
    Guake is a top-down terminal for Gnome, and is highly inspirated by the famous terminal used in quake
builddeps  :
    - pkgconfig(dbus-python)
    - pkgconfig(gconf-2.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(keybinder)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - pkgconfig(pyvte)
    - gnome-common
    - python-notifier
    - pyxdg
rundeps    :
    - gnome-python
    - keybinder
    - libutempter
    - notify-python
    - pyxdg
    - vte2
setup      : |
    %patch -p1 < $pkgfiles/0001-remove-vte-check.patch
    %autogen
build      : |
    %make
install    : |
    %make_install
