name       : guake 
version    : 0.8.5
release    : 1
source     :
    - https://github.com/Guake/guake/archive/0.8.5.tar.gz : c9aee4dcbeb605ab3677438992371aab94a886be8ba3b9cd3f70e8cfcd1560d6
license    : GPL-2.0 # CHECK ME
component  : desktop.gnome 
summary    : Dropdown terminal utilizing Gnome-terminal
description: |
        Guake is a top-down terminal for Gnome, and is highly inspirated by the famous terminal used in quake
builddeps  : 
        - pkgconfig(python2)
        - pkgconfig(x11)
        - pkgconfig(glib-2.0)
        - pkgconfig(gtk+-2.0)
        - pkgconfig(pygtk-2.0)
        - pkgconfig(gconf-2.0)
        - pkgconfig(pyvte)
        - pkgconfig(python-3.5)
        - pkgconfig(dbus-python)
        - pkgconfig(keybinder)
        - vte2
        - pyxdg
        - python-notifier
        - python-gtk2
        - gnome-common
rundeps    :
        - vte2
        - keybinder
        - gnome-python
        - pyxdg
        - notify-python 
        - libutempter
setup      : |
        %patch -p1 < $pkgfiles/0001-remove-vte-check.patch
        ./autogen.sh
        %configure
build      : |
    %make
install    : |
    %make_install
